---

- hosts: all_servers
  become: true
  tasks:

  - name: Install required packages
    apt:
      name:
       - wget
       - python3-psycopg2
       - acl
      state: latest

  - name: Set up Postgres 13 repo
    shell: |
     echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list
     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
    args:
     warn: no	

  - name: Install postgresql
    apt:
     name: postgresql-13
     update_cache: yes



