---
- hosts: all_servers
  become: true
  become_user: root
  
  tasks:
  - name: installation of netbox
    shell: |
      cd /opt
      rm -rf netbox
      sudo git clone -b master https://github.com/netbox-community/netbox.git

  - name: create netbox system user
    shell: |
      sudo adduser --system --group netbox
      sudo chown --recursive netbox /opt/netbox/netbox/media/

  - name: Copy configuration.py
    template:
     src: configuration.py
     dest: /opt/netbox/netbox/netbox/configuration.py
     mode: 0644
     owner: root
     group: root

  - name: execute upgrade.sh
    shell: |
      sudo /opt/netbox/upgrade.sh

  #create superuser manually
  #source /opt/netbox/venv/bin/activate
#(venv) cd /opt/netbox/netbox
#(venv) python3 manage.py createsuperuser

  - name: setup middleware - gunicorn
    shell: |
      sudo cp /opt/netbox/contrib/gunicorn.py /opt/netbox/gunicorn.py

  - name: startup configuration for netbox
    shell: |
      sudo cp -v /opt/netbox/contrib/*.service /etc/systemd/system/
      sudo systemctl daemon-reload
      sudo systemctl start netbox
      sudo systemctl start netbox-rq
      sudo systemctl enable netbox
      sudo systemctl enable netbox-rq
      sudo systemctl status netbox netbox-rq


  
      



    
